[build]
  publish = "."
  functions = "functions"
  command = "npm install"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[functions."functions/scheduledTweet.js"]
  schedule = "0 */2 * * *"

[dev]
  publish = "."
  port = 8888
  autoLaunch = false