name: Scheduled Tweet Posting

on:
  schedule:
    # Runs every 2 hours
    - cron: '0 */2 * * *'
  workflow_dispatch: # Allows manual triggering for testing

jobs:
  post-tweet:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
      
      - name: Create env file
        run: |
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "TWITTER_API_KEY=${{ secrets.TWITTER_API_KEY }}" >> .env
          echo "TWITTER_API_KEY_SECRET=${{ secrets.TWITTER_API_KEY_SECRET }}" >> .env
          echo "TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }}" >> .env
          echo "TWITTER_ACCESS_TOKEN_SECRET=${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}" >> .env

      - name: Run tweet script
        run: |
          node -e "
          const TwitterBot = require('../../src/utils/TwitterBot');
          
          async function postTweet() {
            try {
              const result = await TwitterBot.handler();
              console.log('Tweet posted successfully:', result);
            } catch (error) {
              console.error('Error posting tweet:', error);
              process.exit(1);
            }
          }
          
          postTweet();
          "