name: Scheduled Tweet Posting

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  post-tweet:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
      
      - name: Create env file
        run: |
          touch .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "TWITTER_API_KEY=${{ secrets.API_KEY }}" >> .env
          echo "TWITTER_API_KEY_SECRET=${{ secrets.API_SECRET }}" >> .env
          echo "TWITTER_ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}" >> .env
          echo "TWITTER_ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_SECRET }}" >> .env
      
      - name: Print env variables for testing
        run: |
          echo "PORT=${{ secrets.PORT }}"
          echo "TWITTER_API_KEY=${{ secrets.API_KEY }}"
          echo "TWITTER_API_KEY_SECRET=${{ secrets.API_SECRET }}"
          echo "TWITTER_ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}"
          echo "TWITTER_ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_SECRET }}"
          
      - name: Run tweet script
        run: |
          node -e "
          const TwitterBot = require('./src/utils/TwitterBot');
          
          async function postTweet() {
            try {
              console.log('Starting tweet post...');
              const result = await TwitterBot.handler();
              console.log('Tweet posted successfully:', result);
              process.exit(0);
            } catch (error) {
              console.error('Error posting tweet:', error);
              process.exit(1);
            }
          }
          
          postTweet();
          "